-- TeknorixJobOpeningsDB.sql

-- Create the database if it doesn't exist
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'TeknorixJobOpeningsDB')
BEGIN
    CREATE DATABASE [TeknorixJobOpeningsDB];
END;
GO

USE [TeknorixJobOpeningsDB];
GO

-- Drop tables if they exist to ensure a clean slate for re-runs
IF OBJECT_ID('dbo.Jobs', 'U') IS NOT NULL DROP TABLE dbo.Jobs;
IF OBJECT_ID('dbo.Departments', 'U') IS NOT NULL DROP TABLE dbo.Departments;
IF OBJECT_ID('dbo.Locations', 'U') IS NOT NULL DROP TABLE dbo.Locations;
GO

-- Create Locations Table
CREATE TABLE Locations (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Title NVARCHAR(255) NOT NULL,
    City NVARCHAR(100) NOT NULL,
    State NVARCHAR(100) NOT NULL,
    Country NVARCHAR(100) NOT NULL,
    Zip NVARCHAR(20) NOT NULL
);
GO

-- Create Departments Table
CREATE TABLE Departments (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Title NVARCHAR(255) NOT NULL UNIQUE
);
GO

-- Create Jobs Table
CREATE TABLE Jobs (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Code NVARCHAR(50) NOT NULL UNIQUE, -- Autogenerated on the server
    Title NVARCHAR(255) NOT NULL,
    Description NVARCHAR(MAX) NOT NULL,
    LocationId INT NOT NULL,
    DepartmentId INT NOT NULL,
    PostedDate DATETIME2 NOT NULL,
    ClosingDate DATETIME2 NOT NULL,
    CONSTRAINT FK_Jobs_Locations FOREIGN KEY (LocationId) REFERENCES Locations(Id),
    CONSTRAINT FK_Jobs_Departments FOREIGN KEY (DepartmentId) REFERENCES Departments(Id)
);
GO

-- Insert Sample Data into Locations
INSERT INTO Locations (Title, City, State, Country, Zip) VALUES
('US Head Office', 'Baltimore', 'MD', 'United States', '21202'),
('India Office', 'Bangalore', 'Karnataka', 'India', '560001'),
('UK Office', 'London', 'England', 'United Kingdom', 'SW1A 0AA');
GO

-- Insert Sample Data into Departments
INSERT INTO Departments (Title) VALUES
('Software Development'),
('Project Management'),
('Human Resources'),
('Quality Assurance');
GO

-- Insert Sample Data into Jobs
-- Note: 'Code' and 'PostedDate' would typically be generated by the application.
-- For this script, we'll manually insert them as examples.
-- In a real app, the job creation API generates the Code and PostedDate.
INSERT INTO Jobs (Code, Title, Description, LocationId, DepartmentId, PostedDate, ClosingDate) VALUES
('JOB-DEV-001', 'Software Developer', 'Exciting opportunity for a skilled Software Developer.', 2, 1, GETDATE(), DATEADD(month, 1, GETDATE())),
('JOB-PM-002', 'Project Manager', 'Lead our innovative projects from conception to completion.', 1, 2, GETDATE(), DATEADD(day, 15, GETDATE())),
('JOB-QA-003', 'QA Engineer', 'Ensure the quality of our cutting-edge software solutions.', 2, 4, GETDATE(), DATEADD(month, 2, GETDATE())),
('JOB-HR-004', 'HR Specialist', 'Join our dynamic HR team and help us build a great workplace.', 1, 3, GETDATE(), DATEADD(week, 3, GETDATE()));
GO